name: mirror

on:
  workflow_dispatch:
  schedule:
    - cron: "37 3 */1 * *"

permissions:
  contents: write

jobs:
  mirror-gmp:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: github.repository_owner == 'jevinskie' # prevent from running on a fork
    env:
      src_hg_repo: https://gmplib.org/repo/gmp

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: '${{ secrets.TS_OAUTH_CLIENT_ID }}'
          oauth-secret: '${{ secrets.TS_OAUTH_SECRET }}'
          tags: tag:ci-gmp
          version: latest

      - name: use named exit node in tailscale
        run: |
          timeout 90s sudo -E tailscale set --exit-node=nitro

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        # if: true # debug
        if: false # no-debug

      - name: Retrieve the tip revision ID
        id: retrieve-tip-id
        run: |
          id=`hg id -r tip $src_hg_repo`
          echo "id=$id" >> "$GITHUB_OUTPUT"

      - uses: actions/cache/restore@v4
        id: check-cache
        with:
          path: /proc/version # contents of file are not used
          key: ${{ github.job }}-last-hg-tip-id-${{ steps.retrieve-tip-id.outputs.id }}
          lookup-only: true

      - name: Check day of week
        id: day-of-week
        run: |
          if date +"%u" | grep -q 7; then
            # Always run a full clone on Sundays
            echo "Running weekly full clone (to pick up possible branch/tag changes that happened without a default branch commit)"
            echo "force-run=true" >> "$GITHUB_OUTPUT"
          fi

      - name: mirror https://gmplib.org/repo/gmp to https://github.com/jevinksie/gmp
        id: mirror
        if: steps.check-cache.outputs.cache-hit != 'true' || steps.day-of-week.outputs.force-run == 'true'
        uses: 'mozillazg/mirror-hg-repo@v2'
        with:
          source-hg-repo-url: '${{ env.src_hg_repo }}'
          destination-git-repo-owner: 'jevinskie'
          destination-git-repo-name: 'gmp'
          destination-git-personal-token: '${{ secrets.PERSONAL_GIT_TOKEN }}'

      - uses: actions/cache/save@v4
        if: steps.mirror.outcome == 'success'
        with:
          path: /proc/version # contents of file are not used
          key: ${{ github.job }}-last-hg-tip-id-${{ steps.retrieve-tip-id.outputs.id }}

      - uses: gautamkrishnar/keepalive-workflow@v2

  # disabled
  mirror-gmp-6_3:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: false && github.repository_owner == 'jevinskie' # prevent from running on a fork
    env:
      src_hg_repo: https://gmplib.org/repo/gmp-6.3

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Retrieve the tip revision ID
        id: retrieve-tip-id
        run: |
          id=`hg id -r tip $src_hg_repo`
          echo "id=$id" >> "$GITHUB_OUTPUT"

      - uses: actions/cache/restore@v4
        id: check-cache
        with:
          path: /proc/version # contents of file are not used
          key: ${{ github.job }}-last-hg-tip-id-${{ steps.retrieve-tip-id.outputs.id }}
          lookup-only: true

      - name: Check day of week
        id: day-of-week
        run: |
          if date +"%u" | grep -q 7; then
            # Always run a full clone on Sundays
            echo "Running weekly full clone (to pick up possible branch/tag changes that happened without a default branch commit)"
            echo "force-run=true" >> "$GITHUB_OUTPUT"
          fi

      - name: mirror https://gmplib.org/repo/gmp-6.3 to https://github.com/jevinksie/gmp-6.3
        id: mirror
        if: steps.check-cache.outputs.cache-hit != 'true' || steps.day-of-week.outputs.force-run == 'true'
        uses: 'mozillazg/mirror-hg-repo@v2'
        with:
          source-hg-repo-url: '${{ env.src_hg_repo }}'
          destination-git-repo-owner: 'jevinskie'
          destination-git-repo-name: 'gmp-6.3'
          destination-git-personal-token: '${{ secrets.PERSONAL_GIT_TOKEN }}'

      - uses: actions/cache/save@v4
        if: steps.mirror.outcome == 'success'
        with:
          path: /proc/version # contents of file are not used
          key: ${{ github.job }}-last-hg-tip-id-${{ steps.retrieve-tip-id.outputs.id }}

  # GMP 6.2: disabled, no changes since 2021.
  mirror-gmp-6_2:
    if: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: mirror https://gmplib.org/repo/gmp-6.2 to https://github.com/jevinksie/gmp-6.2
        uses: 'mozillazg/mirror-hg-repo@v2'
        with:
          source-hg-repo-url: 'https://gmplib.org/repo/gmp-6.2'
          destination-git-repo-owner: 'jevinskie'
          destination-git-repo-name: 'gmp-6.2'
          destination-git-personal-token: '${{ secrets.PERSONAL_GIT_TOKEN }}'

  # GMP 6.1: disabled, no changes since 2018.
  mirror-gmp-6_1:
    if: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: mirror https://gmplib.org/repo/gmp-6.1 to https://github.com/jevinksie/gmp-6.1
        uses: 'mozillazg/mirror-hg-repo@v2'
        with:
          source-hg-repo-url: 'https://gmplib.org/repo/gmp-6.1'
          destination-git-repo-owner: 'jevinskie'
          destination-git-repo-name: 'gmp-6.1'
          destination-git-personal-token: '${{ secrets.PERSONAL_GIT_TOKEN }}'

  # GMP 6.0: disabled, no changes since 2014.
  mirror-gmp-6_0:
    if: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: mirror https://gmplib.org/repo/gmp-6.0 to https://github.com/jevinksie/gmp-6.0
        uses: 'mozillazg/mirror-hg-repo@v2'
        with:
          source-hg-repo-url: 'https://gmplib.org/repo/gmp-6.0'
          destination-git-repo-owner: 'jevinskie'
          destination-git-repo-name: 'gmp-6.0'
          destination-git-personal-token: '${{ secrets.PERSONAL_GIT_TOKEN }}'

  # GMP 5.1: disabled, no changes since 2014.
  mirror-gmp-5_1:
    if: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: mirror https://gmplib.org/repo/gmp-5.1 to https://github.com/jevinksie/gmp-5.1
        uses: 'mozillazg/mirror-hg-repo@v2'
        with:
          source-hg-repo-url: 'https://gmplib.org/repo/gmp-5.1'
          destination-git-repo-owner: 'jevinskie'
          destination-git-repo-name: 'gmp-5.1'
          destination-git-personal-token: '${{ secrets.PERSONAL_GIT_TOKEN }}'

  # GMP 5.0. Disabled, no changes since 2012.
  mirror-gmp-5_0:
    if: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: mirror https://gmplib.org/repo/gmp-5.0 to https://github.com/jevinksie/gmp-5.0
        uses: 'mozillazg/mirror-hg-repo@v2'
        with:
          source-hg-repo-url: 'https://gmplib.org/repo/gmp-5.0'
          destination-git-repo-owner: 'jevinskie'
          destination-git-repo-name: 'gmp-5.0'
          destination-git-personal-token: '${{ secrets.PERSONAL_GIT_TOKEN }}'
